name: Check

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - run: uv sync --all-extras
    - run: uv run ruff check .

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - run: uv sync --all-extras
    - run: uv run ruff format . --diff

  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - run: uv sync --all-extras
    - run: uv run basedpyright .
