
name: Python Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
        pip install black flake8 isort mypy pylint pydocstyle pytest
        yes | mypy --install-types
        
    - name: Run black
      run: black .
      continue-on-error: true

    - name: Run flake8
      run: flake8 .
      continue-on-error: true
    
    - name: Run isort
      run: isort .
      continue-on-error: true

    - name: Run mypy
      run: mypy .
      continue-on-error: true
    
    - name: Run pylint
      run: pylint .
      continue-on-error: true
    
    - name: Run pydocstyle
      run: pydocstyle .
      continue-on-error: true
    
    # - name: Run tests
    #   run: pytest
    #   continue-on-error: true

    - name: Build package
      run: python -m build
      continue-on-error: true
